apiVersion: v1
kind: Service
metadata:
  name: {{ include "groundx-web-ui.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "groundx-web-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "groundx-web-ui.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
